name = Landing
description = A stacked grid 3 column layout.
preview = preview.png
template = landing-layout

; Regions
regions[header]               = Header
regions[navigation]           = Navigation bar
regions[preface]              = Preface
regions[highlighted]          = Highlighted
regions[help]                 = Help
regions[content]              = Content
regions[sidebar_first]        = First sidebar
regions[sidebar_second]       = Second sidebar
regions[postscript_first]     = First postscript
regions[postscript_second]    = Second postscript
regions[postscript_third]     = Third postscript
regions[footertop_first]      = Footertop first
regions[footertop_second]     = Footertop second
regions[footertop_third]      = Footertop third
regions[connections]          = Connections
regions[footer]               = Footer

; Stylesheets
stylesheets[all][] = css/layouts/landing/landing.layout.css
