name = Bricks
description = A stacked grid 3 column layout.
preview = preview.png
template = bricks-layout

; Regions
regions[header]               = Header
regions[navigation]           = Navigation bar
regions[preface]              = Preface
regions[highlighted]          = Highlighted
regions[help]                 = Help
regions[content]              = Content
regions[postscript_first]     = First postscript
regions[postscript_second]    = Second postscript
regions[sidebar_first]        = First sidebar
regions[sidebar_second]       = Second sidebar
regions[footer]               = Footer

; Stylesheets
stylesheets[all][] = css/layouts/bricks/bricks.layout.css
